# SPDX-FileCopyrightText: 2026 Duncan McDougall <duncan.mcdougall@rfi.ac.uk>
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "ms-nexus-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
license = "Apache-2.0"
license-files = ["LICENSES/*"]

[project.scripts]
ms-nexus-tools = "ms_nexus_tools:main"
ION2RFI = "ms_nexus_tools:ION2RFI"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
